package com.salim.mydevicetracker.networking

import com.salim.mydevicetracker.devices.DevicesSchema

/***
 * This is the fake api service that we will be using in assignment, in place of the real
 * api service that would normally have generated by Retrofit. @see [DeviceApiService]
 */
class FakeApiService(): DeviceApiService {

    private fun returnFakeJson(): String {
        return ""
    }

    override suspend fun getListOfDevices(): List<DevicesSchema> {
        return listOf()
    }
}